FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install software-properties-common -y && \
    add-apt-repository -y ppa:ethereum/ethereum && \
    apt-get update && \
    apt-get install -y ethereum

RUN mkdir -p /opt/datadir && mkdir -p /opt/enode-registry

VOLUME /opt/datadir

VOLUME /opt/enode-registry

COPY enode-write.sh /

EXPOSE 8545 8546 30303 30303/udp 30304/udp 6060

ENV HOST_NAME="<host-name>"

ENTRYPOINT ["bash", "/enode-write.sh"]
