version: '3'
services:
  genesis:
    image: "eth-genesis:latest"
    networks:
      - ethnet
    volumes:
      - genesis-node-datadir:/opt/datadir
  genesis-enode-writer:
    image: "eth-writer:latest"
    networks:
      - ethnet
    volumes:
      - genesis-node-datadir:/opt/datadir
      - enode-registry:/opt/enode-registry
    depends_on:
      - genesis
networks:
  ethnet:
    driver: bridge
volumes:
  enode-registry:
  genesis-node-datadir: